### ISSUE TITLE
Error: SHA256 mismatch

### ISSUE THREAD

**Issue by willdurand** [hawkw/homebrew-grub#1]
Hallo!

I have just used your tap to install `grub` and it seems the `objconv` archive has changed in April (2017). Hence, the checksum is not correct anymore. This is a bit tricky because the homepage of the objconv's maintainer does not list different archives for the different versions, so I guess updating the checksum would be the only thing to do... WDYT?

```
Error: SHA256 mismatch
Expected: 01bc452c334e3105a516ffcab854b9af2b71c9505fd05681848b051ebf8337f4
Actual: fbb50d84279ed6f38304cd199f56a2ef46cebf136c2611078b97ec2b3f3ce636
Archive: /Users/william/Library/Caches/Homebrew/objconv-2.42.zip
```

Cheers,
W.

**Comment by hawkw** [comment]
> the homepage of the objconv's maintainer does not list different archives for the different versions

Yeah, that's been a pain in my side for a while; it's also why this formula wasn't merged into `homebrew-core`. I think the right thing to do is just to update the SHA, even though that makes me feel a bit dirty.

There is a  [git mirror of `objconv`](https://github.com/vertis/objconv) set up by @vertis a while ago, which we _could_ install from, but it's >3 years out of date.

I really wish there were correctly versioned `objconv` binaries available somewhere, but short of bugging the guy, this is the Right Thing to do...

**Comment by hawkw** [comment]
@willdurand, I've updated the hash and version. Let me know if you have any other problems installing!

**Comment by willdurand** [comment]
looks good to me, thanks!
